### ISSUE TITLE
Collection detail page

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#137]
The collection detail page is essentially the "landing page" for collection-level information. This issue is an epic and exists to aggregate additional tickets.

* [x] Collection detail page MVP #138
* [x] Collection detail page - overview with full detail and navigation #144
* [x] Collection detail page - context sidebar on overview #145 
* [x] Collection detail page - contents/inventory section #149
* [x] Collection detail page - search within MVP #146 
* [ ] ~**epic** Collection detail page - search within enhanced #147~ Treating as separate.

**Comment by anarchivist** [comment]
## Collection detail - overview (with inventory)

![Collection detail overview (with inventory)](https://cloud.githubusercontent.com/assets/73732/25075446/ae947da6-22c9-11e7-841f-c08a24cb11c4.jpg)

## Collection detail - overview (without inventory)

![collection-detail-overview-no-inventory](https://cloud.githubusercontent.com/assets/73732/25075455/db18cd5a-22c9-11e7-9ed6-abc8c9bd6cc6.jpg)

## Collection detail - inventory

![Collection detail - inventory](https://cloud.githubusercontent.com/assets/73732/25075473/4b13f094-22ca-11e7-98b0-2d2c5d6c240e.jpg)

**Comment by anarchivist** [comment]
## Collection detail - overview (without inventory)

![collection-detail-overview-no-inventory](https://cloud.githubusercontent.com/assets/73732/25075455/db18cd5a-22c9-11e7-9ed6-abc8c9bd6cc6.jpg)

**Comment by anarchivist** [comment]
## Collection detail - inventory

![Collection detail - inventory](https://cloud.githubusercontent.com/assets/73732/25075473/4b13f094-22ca-11e7-98b0-2d2c5d6c240e.jpg)
