### ISSUE TITLE
Demo site: how do we add new finding aids/update the index?

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#209]
Currently, the demo site has only one sample finding aid, which is an older version of the fixture we've been developing against. We need a consistent way to populate more known-good (or known-good-enough) finding aids to be able to present real data. 

**Subtasks**

- [x] 1. How do we want to update the index? At deploy time, or something else? Currently: at deploy time.
- [x] 2. Where are the files stored to populate the index? Currently here: https://github.com/sul-dlss/arclight-demo/tree/master/data/ead
- [ ] 3. Will these files be part of the demo repo forever or will there be a plan to do something else? Currently: no plan
- [x] 4. Do we, or are we already validating the data we index into the demo site? Currently: no.
- [ ] 5. What is the process for adding a new EAD to the demo? Currently: ad-hoc with testing on laptop then putting in demo repo.

**Comment by mejackreed** [comment]
Indexed data for the demo instance is housed here: https://github.com/sul-dlss/arclight-demo/tree/master/data/ead

And I believe this is updated on deploy (a commit to `master` triggers this).

Anything else we need to do to successfully complete this ticket?

**Comment by jkeck** [comment]
This ticket is to begin discussion/investigation into how we might allow the demo-site to diverge from our fixture data (and what the implications for that are, etc).  I think there are more questions than answers for this particular ticket right now, but @anarchivist would like us to start exploring answers to these questions.

For instance, is it the expectation that all of the data that the demo site will operate on will be checked into git? (That could potentially be a lot of data)  If so, will it be part of the demo repo forever or will there be a plan to do something else?  When @anarchivist wants to throw addl. data in the demo, what should that process look like?  Do we, or are we already validating the data we index into the demo site?

We should probably define more acceptance criteria for what success for this issue might look like

**Comment by anarchivist** [comment]
Yes, we identified getting more "real" sample data into the demo app as a goal for this sprint. I'm happy to do some local sanity checking by indexing the data to an app running locally, but it'd be nice to throw some known-good or "known-good enough" finding aids to the demo site.

**Comment by drh-stanford** [comment]
I've added some numbered subtasks for this ticket at the top so that we can try to make progress toward resolving this ticket.

Some ideas:

1. Indexing at deploy time sounds like the easiest because the deploy pipeline is automated via AWS. You can, technically, ssh into the box and run rake tasks but that requires access to the AWS accounts and whatnot.

2. I think github is the easiest. The demo repo is distinct from the arclight repo so only we'll need to manage/clone it. I'm not sure what a good alternative would be -- maybe S3 buckets?

3. shrug

4. I'd vote to migrate the validation code to a rake task so that we can run it at deploy and at development time.

5. This begs the question of whether we need a staging server for the demo. So that we can add EADs to a stage server, try it out safely (the EADs may fail to index, for example), and on success, put the EADs into the demo `master` branch via a PR.

**Comment by anarchivist** [comment]
I think we've satisfied 1, 2, and 4 based on @drh-stanford's thoughts. 3 and 5 remain an open question for me.

**Comment by anarchivist** [comment]
There's an open question here about what we're doing over the longer term - a staging server might be nice to be able to index without developer intervention. Staging server might be nice to have locally. 

In any event, this may be out of scope for the MVP work cycle.

**Comment by drh-stanford** [comment]
We discussed not having a staging server for the MVP. If we're in agreement about that, should we close this ticket?

**Comment by anarchivist** [comment]
👍

**Comment by anarchivist** [comment]
Meeting w/ @eefahy 6/15/17:

We're looking at separating indexing from deployment. Current plan (as part of some work to prep for the SPEC demo in July):

* Bump up box size
* Separate indexing from deployment. Deployment needs to include a step to download or checkout EAD files to index. (We can probably still use the directory within the arclight-demo repo if we want, or could break it out into a separate repo)
* Indexing will happen via cron job; planning on it running daily. 
* @eefahy will get me some degree of access to the demo box in case I need to index manually or diagnose when things go wrong.
