### ISSUE TITLE
Structured repository information and repositories page

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#222]
**Subtasks**

- [x] Support for file-backed `Repository` class - see #251
- [x] Load configuration file via generator - see #251
- [x] Add header for Repositories - see #260
- [x] Page to display all repositories - see #260
- [x] Add breadcrumbs - see #260
- [x] Update styling - see #290 
- [ ] Linkify repository name - see #295 
- [ ] Linkify contact email address (mailto link) - see #295 

**Acceptance criteria**

* Ability to define structured information about a repository 
    * Note: I'm neutral on the specific implementation; admin UI mockups suggest this should be admin user editable within that interface. This could be file-backed for now.
    * Identifier or slug (required)
    * Repository name (required)
    * Location
         * Building
         * Address 1
         * Address 2
         * City
         * State
         * ZIP
         * Country
    * Contact phone number
    * Contact information
    * Description
    * Thumbnail (just a URL to the thumbnail is fine for now)
* Display a repositories landing page
    * Display shared application header
         * Indication that the "Repositories" page is active should be clear
    * Display all repositories defined
    * For each repository, display all structured information as defined above [this will be a partial used in other contexts]
    * A route for the page (e.g. `/repositories`)
    * Breadcrumb link leads back to the application home page

**Out of scope**

* Count of collections
* "Learn more" link

**Mockup**

![repositories landing](https://cloud.githubusercontent.com/assets/73732/25540772/1662a0bc-2c01-11e7-869a-5a133bc604c1.jpg)

**Comment by drh-stanford** [comment]
Do we want to store this information in a hand-edited `repository.yml` file only? Or should we be using an ActiveRecord model `Arclight::Repository` and use `db/seeds.rb` to load the data into the database?

I'm assuming that we'll need to do the latter eventually if we have an Admin UI that can customize these data. If that's a correct assumption, should we take the time to do a database-backed implementation now?

**Comment by jkeck** [comment]
I wonder if we could get away w/ a PORO that reads from a `repository.yml` that has an ActiveRecord like interface (maybe implements `where` and `all`) to allow use to easily swap out.

This way we don't need to worry about seeds, schema, etc until we're actually ready to make the records creatable via a UI.

**Comment by drh-stanford** [comment]
Ok, that sounds good. So I'll create a Repository data class that has a `from_yaml` and a couple finder methods and that should lend its way to migrating to ActiveRecord if we need to.

**Comment by drh-stanford** [comment]
@anarchivist Do we want "City, State, ZIP" or "City, State, Country" or "City, State, ZIP, Country"? The mockup and the ticket differ for the location information.

**Comment by anarchivist** [comment]
@drh-stanford City, State, ZIP, Country.

**Comment by drh-stanford** [comment]
Below is a rough cut of the repository partials that contain all of the data for this ticket. TBD is the styling, breadcrumbs, and header.

![screen shot 2017-05-02 at 3 28 12 pm](https://cloud.githubusercontent.com/assets/1861171/25642078/5d0d02a2-2f4c-11e7-91f7-90d49afc9e73.png)

**Comment by drh-stanford** [comment]
I've finished all the TBDs except for the final styling and it's in PR #260.
