### ISSUE TITLE
Component detail: display context hierarchy

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#240]
**Acceptance criteria**

On the component detail page (#232):

* [x] Display a new section entitled "Collection context" and brief collection-level information #298

* [x] Display a partial hierarchy of the collection - ancestors only #299
* [x] Visually distinguish ("highlight") the component for which the current show page is active #301
* [x] Display a partial hierarchy of the collections with siblings #300

**Mockup**

![after](https://cloud.githubusercontent.com/assets/73732/25595704/9db8fcca-2e7a-11e7-8eae-4c0ea5aa57c2.jpg)
