### ISSUE TITLE
Deploy application in AWS

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/arclight#92]
**Acceptance criteria**

* A publicly accessible instance of ArcLight 
* A sample set of data indexed in the application
  * Whatever fixtures we're currently using

## TODOs

- [x] Build application repo (`arclight-demo`) - #165 
- [x] Decide on AWS requirements
  - [x] Arclight rails (nginx)
  - [x] Solr (via projectblacklight.org AWS account)
  - [x] RDS database (MySQL mode) - and external instance
  - [x] Fixture data
  - [x] Setup DNS
- [x] Add deploy scripts
   - [x] Triggered on `arclight-demo/master` commits (e.g., rev `Gemfile*`) for new releases of Arclight
   - [x] Runs `db:migrate` and `arclight:seed`s?
  - [x] Travis
  - [x] AWS codepipeline

**Comment by drh-stanford** [comment]
@eefahy and I had an initial discussion about this ticket. It's really an epic ticket so we may want to break it down into smaller tickets, but for the time being we added a TODO section with subtasks into this ticket.

**Comment by jkeck** [comment]
IMO this should be a generic instance (i.e. non-Stanford branded).

**Comment by mejackreed** [comment]
Yeah.. Ideally zero branding or mods to this the better.

**Comment by anarchivist** [comment]
This should absolutely be a generic, non-Stanford branded instance.

**Comment by drh-stanford** [comment]
http://arclight-demo.projectblacklight.org

**Comment by mejackreed** [comment]
👏
